apiVersion: v1
kind: Service
metadata:
  name: mongodb-0
spec:
  selector:
    app: mongodb
    apps.kubernetes.io/pod-index: "0"
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-1
spec:
  selector:
    app: mongodb
    apps.kubernetes.io/pod-index: "1"
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-2
spec:
  selector:
    app: mongodb
    apps.kubernetes.io/pod-index: "2"
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017