apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongod-config
          configMap:
            name: mongod-config
      containers:
      - name: mongodb
        image: mongodb/mongodb-community-server:6.0-ubi8
        command: ["mongod", "--config", "/etc/mongod.conf"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: mongod-config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: hcloud-volumes
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi