apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-upgrade-1
  labels:
    app: mongodb-upgrade-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-upgrade-1
  template:
    metadata:
      labels:
        app: mongodb-upgrade-1
    spec:
      volumes:
        - name: mongod-config
          configMap:
            name: mongod-config
        - name: data
          persistentVolumeClaim:
            claimName: data-mongodb-1
      containers:
      - name: mongodb
        image: mongodb/mongodb-community-server:6.0-ubi8
        command: ["mongod", "--config", "/etc/mongod.conf"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 27017
          name: mongodb
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: mongod-config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-1
spec:
  selector:
    app: mongodb-upgrade-1
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017