apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dorilahav/k8s-apps.git
    path: test
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
      selfHeal: true