apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hetzner-csi
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.hetzner.cloud
    chart: hcloud-csi
    targetRevision: 2.18.3
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true