apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: protein-prod
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - type: prod
  template:
    metadata:
      name: "protein-{{ printf "{{.type}}" }}"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/dorilahav/k8s-apps.git
        path: "protein-{{ printf "{{.type}}" }}"
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: "protein-{{ printf "{{.type}}" }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true