apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: protein-prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
  - repoURL: https://github.com/dorilahav/k8s-apps.git
    path: charts/static-site
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/protein-prod/values.yaml
  - repoURL: https://github.com/dorilahav/k8s-apps.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: protein-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
