apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: protein-intake-calculator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dorilahav/k8s-apps.git
    path: protein-prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: protein-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true