apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dorilahav/k8s-apps.git
    path: rabbitmq-cluster-operator
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-operator
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true