apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-test-cluster
spec:
  replicas: {{ .Values.replicas }}
  service:
    type: NodePort
  persistence:
    storageClassName: hcloud-volumes
    storage: {{ .Values.storage.size }}
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: '1'
      memory: 2Gi
  override:
    service:
      spec:
        ports:
          - name: http
            protocol: TCP
            port: 15672
            targetPort: 15672
            nodePort: {{ .Values.ports.management }}
          - name: amqp
            protocol: TCP
            port: 5672
            targetPort: 5672
            nodePort: {{ .Values.ports.amqp }}
