argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false

  global:
    domain: argocd.dorilahav.com

  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls: false