apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-health-checker
  labels:
    app: mongodb-health-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-health-checker
  template:
    metadata:
      labels:
        app: mongodb-health-checker
    spec:
      containers:
      - name: app
        image: dorimon/mongodb-health-checker:1.0.0
        env:
        - name: MONGO_CONNECTION_STRING
          value: "mongodb://app:abcd1234@mongodb-0,mongodb-1,mongodb-2/test?replicaSet=rs0&authSource=admin"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
